# Generated by Django 3.0.3 on 2020-04-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20200414_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='read',
        ),
        migrations.AlterField(
            model_name='post',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
